#!/usr/bin/env python3
"""Collects the user-facing texts of Torqa into app/translations/torqa.pot (R24).

Sources:
- GDScript: arguments of tr("…") and TranslationServer.translate("…");
- GDScript and Rust: every string literal between `i18n-begin` and `i18n-end` comments
  (lists of names, labels sent from the core) — identifiers and units are skipped;
- scenes: text, tooltip_text, title, ok_button_text and placeholder_text properties;
- app/translations/extra-msgids.txt for texts built at run time.

With --check, fails if the template is outdated or a translation misses texts.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
APP = ROOT / "app"
POT = APP / "translations" / "torqa.pot"
STRING = re.compile(r'"((?:[^"\\]|\\.)*)"')
TR_CALL = re.compile(r'(?:\btr|TranslationServer\.translate)\(\s*"((?:[^"\\]|\\.)*)"')
SCENE_PROPERTY = re.compile(
    r'^(?:text|tooltip_text|title|ok_button_text|placeholder_text) = "((?:[^"\\]|\\.)*)"$'
)


def is_text(value: str) -> bool:
    """Words for people, not identifiers, paths, formats or units."""
    if not re.search(r"[A-Za-z]{2,}", value):
        return False
    if re.fullmatch(r"[a-z0-9_./:-]+", value):  # identifiers, keys, paths
        return False
    return not value.startswith(("res://", "user://"))


def unescape(value: str) -> str:
    return value.encode().decode("unicode_escape").encode("latin-1").decode("utf-8")


def collect() -> dict[str, list[str]]:
    found: dict[str, list[str]] = {}

    def add(msgid: str, where: str) -> None:
        found.setdefault(msgid, [])
        if where not in found[msgid]:
            found[msgid].append(where)

    sources = sorted(APP.rglob("*.gd")) + sorted((ROOT / "core").rglob("*.rs"))
    for path in sources:
        if ".godot" in path.parts or "target" in path.parts or "tests" in path.parts:
            continue
        rel = path.relative_to(ROOT).as_posix()
        in_region = False
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if "i18n-begin" in line:
                in_region = True
                continue
            if "i18n-end" in line:
                in_region = False
                continue
            where = f"{rel}:{number}"
            if path.suffix == ".gd":
                for match in TR_CALL.finditer(line):
                    add(unescape(match.group(1)), where)
            if in_region and not line.lstrip().startswith(("#", "//")):
                for match in STRING.finditer(line):
                    value = unescape(match.group(1))
                    if is_text(value):
                        add(value, where)
    for path in sorted(APP.rglob("*.tscn")):
        if ".godot" in path.parts or "tests" in path.parts:
            continue
        rel = path.relative_to(ROOT).as_posix()
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            match = SCENE_PROPERTY.match(line)
            if match and is_text(unescape(match.group(1))):
                add(unescape(match.group(1)), f"{rel}:{number}")
    extra = APP / "translations" / "extra-msgids.txt"
    for number, line in enumerate(extra.read_text(encoding="utf-8").splitlines(), 1):
        if line.strip() and not line.startswith("#"):
            add(line.strip(), f"app/translations/extra-msgids.txt:{number}")
    return found


def quote(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def template(found: dict[str, list[str]]) -> str:
    lines = [
        "# Torqa user interface texts. Generated by scripts/i18n/extract.py — do not edit.",
        'msgid ""',
        'msgstr ""',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        "",
    ]
    for msgid in sorted(found):
        lines.append("#: " + " ".join(found[msgid]))
        lines.append(f"msgid {quote(msgid)}")
        lines.append('msgstr ""')
        lines.append("")
    return "\n".join(lines)


def translated(po: pathlib.Path) -> dict[str, str]:
    """msgid → msgstr of a .po file (single-line entries, as Torqa writes them)."""
    entries: dict[str, str] = {}
    msgid = None
    for line in po.read_text(encoding="utf-8").splitlines():
        if line.startswith("msgid "):
            msgid = unescape(line[7:-1])
        elif line.startswith("msgstr ") and msgid is not None:
            entries[msgid] = unescape(line[8:-1])
            msgid = None
    entries.pop("", None)
    return entries


def main() -> int:
    found = collect()
    text = template(found)
    if "--check" not in sys.argv:
        POT.write_text(text, encoding="utf-8")
        print(f"{POT.relative_to(ROOT)}: {len(found)} texts")
        return 0
    problems = []
    if not POT.exists() or POT.read_text(encoding="utf-8") != text:
        problems.append("torqa.pot is outdated: run scripts/i18n/extract.py")
    for po in sorted(POT.parent.glob("*.po")):
        entries = translated(po)
        missing = [m for m in found if not entries.get(m)]
        if missing:
            problems.append(f"{po.name} lacks {len(missing)} texts, e.g. {missing[:3]}")
        for msgid, msgstr in entries.items():
            if msgid in found and sorted(re.findall(r"%[-0-9.]*[a-z%]", msgid)) != sorted(
                re.findall(r"%[-0-9.]*[a-z%]", msgstr)
            ):
                problems.append(f"{po.name}: placeholders differ for {msgid!r}")
    for problem in problems:
        print(problem, file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
